# Objetivo del notebook

El objetivo principal de este notebook no es otro que el de analizar los datos de los que partimos para desarrollar el sistema de prediccion.

# Importar las librerias a utilizar

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Cargo el conjunto de datos en memoria como un objeto DataFrame
dataset_route = '../data/hotel_bookings_clean.csv'
bookings_df = pd.read_csv(dataset_route)

# Muestro los 10 primeros registros del dataset
bookings_df.head(10)

,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,deposit_type_No_Deposit,deposit_type_Non_Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,27,1,7,0,0,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,737,27,1,7,0,0,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,7,27,1,7,0,1,1,0.0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,13,27,1,7,0,1,1,0.0,0,...,0,0,0,1,0,0,0,0,1,0
4,0,14,27,1,7,0,2,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
5,0,14,27,1,7,0,2,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
6,0,0,27,1,7,0,2,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
7,0,9,27,1,7,0,2,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
8,1,85,27,1,7,0,3,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
9,1,75,27,1,7,0,3,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0

In [3]:
# Muestro los ultimos 10 registros del dataset
bookings_df.tail(10)

,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,deposit_type_No_Deposit,deposit_type_Non_Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
119200,0,44,35,31,8,1,3,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
119201,0,188,35,31,8,2,3,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
119202,0,135,35,30,8,2,4,3,0.0,0,...,1,0,0,1,0,0,0,0,1,0
119203,0,164,35,31,8,2,4,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
119204,0,21,35,30,8,2,5,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
119205,0,23,35,30,8,2,5,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
119206,0,102,35,31,8,2,5,3,0.0,0,...,0,0,0,1,0,0,0,0,1,0
119207,0,34,35,31,8,2,5,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
119208,0,109,35,31,8,2,5,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
119209,0,205,35,29,8,2,7,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0

In [4]:
# Muestro informacion del dataframe
bookings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119210 entries, 0 to 119209
Data columns (total 53 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   is_canceled                     119210 non-null  int64
 1   lead_time                       119210 non-null  int64
 2   arrival_date_week_number        119210 non-null  int64
 3   arrival_date_day_of_month       119210 non-null  int64
 4   arrival_date_month              119210 non-null  int64
 5   stays_in_weekend_nights         119210 non-null  int64
 6   stays_in_week_nights            119210 non-null  int64
 7   adults                          119210 non-null  int64
 8   children                        119206 non-null  float64
 9   babies                          119210 non-null  int64
 10  is_repeated_guest               119210 non-null  int64
 11  previous_cancellations          119210 non-null  int64
 12  previous_bookings_not_canceled  119210 non-null  int64
 13  required_car_parking_spaces     119210 non-null  int64
 14  total_of_special_requests       119210 non-null  int64
 15  avg_daily_rate                  119210 non-null  float64
 16  booked_by_company               119210 non-null  int64
 17  booked_by_agent                 119210 non-null  int64
 18  hotel_City                      119210 non-null  int64
 19  hotel_Resort                    119210 non-null  int64
 20  meal_BB                         119210 non-null  int64
 21  meal_FB                         119210 non-null  int64
 22  meal_HB                         119210 non-null  int64
 23  meal_No_meal                    119210 non-null  int64
 24  market_segment_Aviation         119210 non-null  int64
 25  market_segment_Complementary    119210 non-null  int64
 26  market_segment_Corporate        119210 non-null  int64
 27  market_segment_Direct           119210 non-null  int64
 28  market_segment_Groups           119210 non-null  int64
 29  market_segment_Offline_TA_TO    119210 non-null  int64
 30  market_segment_Online_TA        119210 non-null  int64
 31  market_segment_Undefined        119210 non-null  int64
 32  distribution_channel_Corporate  119210 non-null  int64
 33  distribution_channel_Direct     119210 non-null  int64
 34  distribution_channel_GDS        119210 non-null  int64
 35  distribution_channel_TA_TO      119210 non-null  int64
 36  distribution_channel_Undefined  119210 non-null  int64
 37  reserved_room_type_A            119210 non-null  int64
 38  reserved_room_type_B            119210 non-null  int64
 39  reserved_room_type_C            119210 non-null  int64
 40  reserved_room_type_D            119210 non-null  int64
 41  reserved_room_type_E            119210 non-null  int64
 42  reserved_room_type_F            119210 non-null  int64
 43  reserved_room_type_G            119210 non-null  int64
 44  reserved_room_type_H            119210 non-null  int64
 45  reserved_room_type_L            119210 non-null  int64
 46  deposit_type_No_Deposit         119210 non-null  int64
 47  deposit_type_Non_Refund         119210 non-null  int64
 48  deposit_type_Refundable         119210 non-null  int64
 49  customer_type_Contract          119210 non-null  int64
 50  customer_type_Group             119210 non-null  int64
 51  customer_type_Transient         119210 non-null  int64
 52  customer_type_Transient-Party   119210 non-null  int64
dtypes: float64(2), int64(51)
memory usage: 48.2 MB

Como se indica en el README adjunto a este analisis, y por tanto, en la descripcion de este conjunto de datos, los datos se encuentran procesados, por lo que no va a ser necesario aplicar preprocesamiento de datos (a excepcion de normalizacion, en columnas en las que esta fuese necesaria).

Por otro lado, podemos ver como dos de las columnas de nuestro dataset almacenan valores de tipo entero, mientras que el resto de columnas, almacenan varioes de tipo flotante.

Por su parte, contamos con unicamente 4 valores nulos registrados en nuestro dataframe. Si es cierto que podria aplicar KNN para estimar los valores faltantes de esta variable, pero al tratarse de la variable 'children', y ser solo 4 ejemplos, voy a optar por eliminar dichos registros de mi dataset.

In [7]:
print(bookings_df.isna().sum())
bookings_df.dropna(inplace = True)

is_canceled                       0
lead_time                         0
arrival_date_week_number          0
arrival_date_day_of_month         0
arrival_date_month                0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
required_car_parking_spaces       0
total_of_special_requests         0
avg_daily_rate                    0
booked_by_company                 0
booked_by_agent                   0
hotel_City                        0
hotel_Resort                      0
meal_BB                           0
meal_FB                           0
meal_HB                           0
meal_No_meal                      0
market_segment_Aviation           0
market_segment_Complementary      0
market_segment_Corporate          0
market_segment_Direct             0
market_segment_Groups             0
market_segment_Offline_TA_TO      0
market_segment_Online_TA          0
market_segment_Undefined          0
distribution_channel_Corporate    0
distribution_channel_Direct       0
distribution_channel_GDS          0
distribution_channel_TA_TO        0
distribution_channel_Undefined    0
reserved_room_type_A              0
reserved_room_type_B              0
reserved_room_type_C              0
reserved_room_type_D              0
reserved_room_type_E              0
reserved_room_type_F              0
reserved_room_type_G              0
reserved_room_type_H              0
reserved_room_type_L              0
deposit_type_No_Deposit           0
deposit_type_Non_Refund           0
deposit_type_Refundable           0
customer_type_Contract            0
customer_type_Group               0
customer_type_Transient           0
customer_type_Transient-Party     0
dtype: int64

Voy a continuar con el analisis de los datos a partir de visualizar distribuciones de los mismos en funcion de algunas de las caracteristicas que tenemos recogidas. 
Continuo en el notebook 'visualizacion_datos.ipynb'